[build-system]
requires = ["setuptools>=64", "versioningit>=1.1.0"]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method="git"
default-tag = "v0.0.0"

[tool.versioningit.write]
file = "src/isal/_version.py"
